# To get started with Dependabot version updates, you will need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github-octocat

registries:
  github-octocat:
    type: git
    url: https://go.lunarway.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT }}
